---
services:
  letterboxarr:
    image: fcote/letterboxarr:latest
    container_name: letterboxarr
    restart: unless-stopped
    environment:
      - RADARR_API_KEY=your_radarr_api_key_here
      - LETTERBOXD_USERNAME=your_letterboxd_username_here
      - RADARR_URL=http://radarr:7878             # Change to your Radarr URL
      - RADARR_QUALITY_PROFILE=1                  # Change to your preferred quality profile ID
      - RADARR_ROOT_FOLDER=/movies                # Change to your movies folder path
      - RADARR_MONITOR_ADDED_MOVIES=true          # Monitor added movies
      - RADARR_START_SEARCHING_ADDED_MOVIES=true  # Start searching for added movies
      - SYNC_INTERVAL_MINUTES=60                  # How often to check for new movies

    volumes:
      - ./data:/app/data  # Persistent storage for tracking processed movies
